services:
  - type: web
    name: endometriosis-rag-api
    env: python
    runtime: python-3.11.9
    buildCommand: "pip install --upgrade pip==23.3.1 setuptools==68.2.2 wheel==0.41.2 && pip install --no-cache-dir -r requirements.txt"
    startCommand: "python rag_api.py"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"