services:
  - type: web
    name: endometriosis-ml-api
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt"
    startCommand: "python predict_api.py"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"